// svelte/src/App.svelte
<script>
  import Card from "./lib/Card.svelte";
  import qrCodeImg from "./assets/qrcode.png";
</script>

<section id="center">
  <Card
    imgSrc={qrCodeImg}
    imgAlt="qrcode"
    title="Improve your front-end skills by building projects"
    desc="Scan the QR code to visit Frontend Mentor and take your coding skills to the next level"
  />
</section>

// vue/src/App.vue
<script setup lang="ts">
import qrCodeImg from "./assets/qrcode.png";
import Card from "./components/card/Card.vue";
</script>

<template>
  <section id="center">
    <Card :title="'Improve your front-end skills by building projects'"
      :desc="'Scan the QR code to visit Frontend Mentor and take your coding skills to the next level'"
      :imgSrc="qrCodeImg" :imgAlt="'qrcode'" />
  </section>
</template>
